name: PyInstaller Cross-Platform Build

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt || true  # Optional

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --add-data "backend:backend" --add-data "resources:resources" --add-data "static:static" --add-data "templates:templates" --windowed --name=EAS --icon "${{ matrix.os == 'windows-latest' && 'resources/icons/easLogo.ico' || (matrix.os == 'macos-latest' && 'resources/icons/easLogo.icns') }}" main.py
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/*
